accounts:
- erpnepal/accounts/*
- erpnepal/controllers/accounts_controller.py
- erpnepal/controllers/taxes_and_totals.py

stock:
- erpnepal/stock/*
- erpnepal/controllers/stock_controller.py
- erpnepal/controllers/item_variant.py

assets:
- erpnepal/assets/*

regional:
- erpnepal/regional/*

selling:
- erpnepal/selling/*
- erpnepal/controllers/selling_controller.py

buying:
- erpnepal/buying/*
- erpnepal/controllers/buying_controller.py

support:
- erpnepal/support/*

POS:
- pos*

ecommerce:
- erpnepal/e_commerce/*

maintenance:
- erpnepal/maintenance/*

manufacturing:
- erpnepal/manufacturing/*

crm:
- erpnepal/crm/*

HR:
- erpnepal/hr/*

payroll:
- erpnepal/payroll*

projects:
- erpnepal/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['erpnepal/**/*.py']
  all: ['!erpnepal/**/test*.py']
